export const field = [
  { name: "Cardiologist", description: "Heart and blood vessels specialist", id: 1 },
  { name: "Dermatologist", description: "Skin, hair, and nail specialist", id: 2 },
  { name: "Neurologist", description: "Nervous system and brain specialist", id: 3 },
  { name: "Pediatrician", description: "Children's health specialist", id: 4 },
  { name: "Orthopedic", description: "Bones and joints specialist", id: 5 },
  { name: "Oncologist", description: "Cancer diagnosis and treatment specialist", id: 6 },
  { name: "Ophthalmologist", description: "Eye and vision care specialist", id: 7 },
  { name: "Psychiatrist", description: "Mental health and behavioral specialist", id: 8 },
  { name: "Gynecologist", description: "Female reproductive health specialist", id: 9 },
  { name: "Endocrinologist", description: "Hormonal and gland-related health specialist", id: 10 },
  { name: "Nephrologist", description: "Kidney function and disease specialist", id: 11 },
  { name: "Urologist", description: "Urinary tract and male reproductive specialist", id: 12 },
  { name: "Gastroenterologist", description: "Digestive system and liver specialist", id: 13 },
  { name: "Rheumatologist", description: "Autoimmune and joint disease specialist", id: 14 },
  { name: "Pulmonologist", description: "Lung and respiratory system specialist", id: 15 },
  { name: "Hematologist", description: "Blood and lymphatic system specialist", id: 16 },
  { name: "Allergist", description: "Allergy and immune system disorder specialist", id: 17 },
  { name: "Otolaryngologist", description: "Ear, nose, and throat specialist (ENT)", id: 18 },
  { name: "Radiologist", description: "Medical imaging and diagnostics specialist", id: 19 },
  { name: "General Surgeon", description: "Specialist in surgical procedures for various conditions", id: 20 },
  { name: "Plastic Surgeon", description: "Cosmetic and reconstructive surgery specialist", id: 21 },
  { name: "Podiatrist", description: "Foot and lower limb specialist", id: 22 },
  { name: "Pathologist", description: "Disease diagnosis through lab tests and samples", id: 23 },
  { name: "Sports Medicine Specialist", description: "Sports-related injuries and rehabilitation", id: 24 },
  { name: "Geriatrician", description: "Elderly care and age-related conditions specialist", id: 25 },
  { name: "Critical Care Specialist", description: "Intensive care and life-threatening condition management", id: 26 },
  { name: "Anesthesiologist", description: "Anesthesia and pain management specialist", id: 27 },
  { name: "Infectious Disease Specialist", description: "Infections and communicable disease specialist", id: 28 },
  { name: "Immunologist", description: "Immune system and autoimmune disorder specialist", id: 29 }
];
